---
clickhouse_database_name: vector_logs
clickhouse_create_table_name: example_logs
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

vector_version: "0.33.0-1"
vector_config:
  sources:
    dummy_logs:
      type: demo_logs
      format: syslog
      interval: 1
  transforms:
    parse_logs:
      inputs:
      - dummy_logs
      source: |-
        . = parse_syslog!(string!(.message))
        .timestamp = to_string(.timestamp)
        .timestamp = slice!(.timestamp, start:0, end: -1)
      type: remap
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - parse_logs
      database: vector_logs
      endpoint: 'http://51.250.14.221:8123'
      table: example_logs
      compression: gzip
  api:
    enabled: true
    address: '0.0.0.0:8686'

